networks:
  busterblock-net:
    name: busterblock-net

services:
  api:
    build: .
    container_name: busterblock_api_container
    restart: unless-stopped
    ports:
      - "8080:8080"
    #depends_on:
     # - db
    volumes:
      - ./app:/code/app
    env_file:
      - .env
    networks:
      - busterblock-net
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    depends_on:
      db:
        condition: service_healthy
        
  tests:
    container_name: tests_api_busterblock
    build: .
    command: pytest -v -s
    volumes:
      - .:/code
    networks:
      - busterblock-net
    depends_on:
      db:
        condition: service_healthy



  db:
    image: mariadb:10.6
    container_name: busterblock_db_container
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/bd/busterblock.ldd:/docker-entrypoint-initdb.d/busterblock.ldd:ro
      - ./docker/bd/busterblock.lmd:/docker-entrypoint-initdb.d/busterblock.lmd:ro
      - ./docker/bd/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./docker/bd/init_test.sql:/docker-entrypoint-initdb.d/init_test.sql:ro

    networks:
        - busterblock-net
    healthcheck:
        test: [ "CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=${MARIADB_ROOT_PASSWORD}" ]
        interval: 5s
        timeout: 3s
        retries: 20

      

volumes:
  db-data: